language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.6
install:
  - pip install -r requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == '2.6' ]]; then
      pip install -r requirements26.txt;
    fi
script:
  - bin/test
